package ltechnologies.onionphone.onionvpn.core.dnscrypt

import ltechnologies.onionphone.onionvpn.core.model.TunnelEndpoints
import ltechnologies.onionphone.onionvpn.core.model.TunnelPreferences

/**
 * DNSCrypt configuration per draft-denis-dprive-dnscrypt + InviZible patterns:
 *
 * - Listen on loopback UDP/TCP (minimal exposure per DNSCrypt spec).
 * - Upstream resolver traffic forced through Tor SOCKS (encrypted DNS over Tor).
 * - Bootstrap/netprobe via Tor DNSPort only — never clearnet/system DNS.
 * - Native sdns:// stamps (SafeSocks-compatible; DoH stamps fail Tor IP checks).
 */
object DnsCryptConfigWriter {
    const val BLOCKED_NAMES_FILE = "blocked-names.txt"

    val knownServers: Map<String, String> = mapOf(
        // Native DNSCrypt stamps (AdGuard) — SafeSocks-compatible through Tor SOCKS.
        "cloudflare" to
            "sdns://AQMAAAAAAAAAETk0LjE0MC4xNC4xNDo1NDQzINErR_JS3PLCu_iZEIbq95zkSV2LFsigxDIuUso_OQhzIjIuZG5zY3J5cHQuZGVmYXVsdC5uczEuYWRndWFyZC5jb20",
        "adguard" to
            "sdns://AQMAAAAAAAAAETk0LjE0MC4xNC4xNDo1NDQzINErR_JS3PLCu_iZEIbq95zkSV2LFsigxDIuUso_OQhzIjIuZG5zY3J5cHQuZGVmYXVsdC5uczEuYWRndWFyZC5jb20",
    )

    fun blockedNamesFileContent(): String = """
        dns.google
        dns.cloudflare.com
        one.one.one.one
    """.trimIndent() + "\n"

    fun write(
        configDirectory: String,
        serverName: String = "cloudflare",
        listenPort: Int = TunnelEndpoints.DNSCRYPT_LISTEN_PORT,
        torSocksPort: Int = TunnelEndpoints.TOR_SOCKS_PORT,
        torDnsPort: Int = TunnelEndpoints.TOR_DNS_PORT,
        preferences: TunnelPreferences = TunnelPreferences(),
    ): String {
        val bootstrap = "${TunnelEndpoints.LOOPBACK}:$torDnsPort"
        // Whonix: DNSCrypt uses its own SocksPort + SOCKS auth (not the app/hev port).
        val proxy =
            "socks5://${TunnelEndpoints.SOCKS_DNSCRYPT_USER}:${TunnelEndpoints.SOCKS_DNSCRYPT_PASS}" +
                "@${TunnelEndpoints.LOOPBACK}:$torSocksPort"
        val name = serverName.ifBlank { preferences.dnsCryptServerName }
        return """
            # Generated by OnionVPN — DNSCrypt upstream forced through Tor (dedicated SocksPort).
            listen_addresses = ['${TunnelEndpoints.LOOPBACK}:$listenPort']
            max_clients = 128
            ipv4_servers = true
            ipv6_servers = false
            dnscrypt_ephemeral_keys = true
            tls_disable_session_tickets = true

            require_dnssec = false
            require_nolog = ${preferences.dnsCryptRequireNoLog}
            require_nofilter = ${preferences.dnsCryptRequireNoFilter}

            force_tcp = ${preferences.dnsCryptForceTcp}
            timeout = 15000
            keepalive = 30

            # Upstream DNSCrypt server connections go through Tor SOCKS (isolated port).
            proxy = '$proxy'

            # Bootstrap and netprobe use Tor DNSPort only.
            bootstrap_resolvers = ['$bootstrap']
            ignore_system_dns = true
            netprobe_address = '$bootstrap'
            netprobe_timeout = 500

            [blocked_names]
              blocked_names_file = '$BLOCKED_NAMES_FILE'

            [static]
              [static.'$name']
                stamp = '${stampFor(name)}'
        """.trimIndent() + "\n"
    }

    fun stampFor(serverName: String): String =
        knownServers[serverName] ?: knownServers.getValue("cloudflare")
}
