package ltechnologies.onionphone.onionvpn.core.dnscrypt.config

import ltechnologies.onionphone.onionvpn.core.model.TunnelEndpoints
import ltechnologies.onionphone.onionvpn.core.model.TunnelPreferences

/**
 * Package `config` — dnscrypt-proxy.toml + blocked-names generation (no process I/O).
 *
 * Imported by [ltechnologies.onionphone.onionvpn.core.dnscrypt.DnsCryptProcessManager]
 * (pipeline step 2: write config) and validation tests.
 */

/**
 * Builds OnionVPN DNSCrypt-proxy config: Tor SOCKS upstream, Tor DNSPort bootstrap,
 * MITM / captive hardening.
 *
 * @see <a href="https://dnscrypt.info/">DNSCrypt</a>
 */
object DnsCryptConfigWriter {
    /** Basename of the blocked_names list written beside the TOML. */
    const val BLOCKED_NAMES_FILE = "blocked-names.txt"

    /**
     * Known static server name → sdns:// stamp (native DNSCrypt; SafeSocks-compatible).
     */
    val knownServers: Map<String, String> = mapOf(
        "cloudflare" to
            "sdns://AQMAAAAAAAAAETk0LjE0MC4xNC4xNDo1NDQzINErR_JS3PLCu_iZEIbq95zkSV2LFsigxDIuUso_OQhzIjIuZG5zY3J5cHQuZGVmYXVsdC5uczEuYWRndWFyZC5jb20",
        "adguard" to
            "sdns://AQMAAAAAAAAAETk0LjE0MC4xNC4xNDo1NDQzINErR_JS3PLCu_iZEIbq95zkSV2LFsigxDIuUso_OQhzIjIuZG5zY3J5cHQuZGVmYXVsdC5uczEuYWRndWFyZC5jb20",
    )

    /**
     * Hostnames blocked to reduce DoH/DoT/captive/OEM side-channels over tunnel DNS.
     */
    fun blockedNamesFileContent(): String = """
        ####################
        # Public DoH / DoT #
        ####################
        dns.google
        dns.google.com
        dns.cloudflare.com
        cloudflare-dns.com
        one.one.one.one
        mozilla.cloudflare-dns.com
        security.cloudflare-dns.com
        chrome.cloudflare-dns.com
        dns.quad9.net
        dns9.quad9.net
        dns10.quad9.net
        dns11.quad9.net
        doh.opendns.com
        doh.dns.sb
        dns.adguard.com
        dns-family.adguard.com
        dns.nextdns.io
        ####################
        # Captive portals  #
        ####################
        connectivitycheck.gstatic.com
        www.gstatic.com
        clients3.google.com
        clients1.google.com
        captive.apple.com
        www.apple.com
        www.msftconnecttest.com
        msftncsi.com
        www.msftncsi.com
        detectportal.firefox.com
        network-test.debian.org
        neverssl.com
        ####################
        # OEM / Android    #
        ####################
        connectivitycheck.android.com
        android.googleapis.com
        play.googleapis.com
    """.trimIndent() + "\n"

    /**
     * @param configDirectory absolute dir for relative blocked_names_file
     * @param serverName key in [knownServers] (fallback cloudflare)
     * @param listenPort loopback stub listener
     * @param torSocksPort DNSCrypt-dedicated Tor SocksPort
     * @param torDnsPort Tor DNSPort for bootstrap/netprobe only
     */
    fun write(
        configDirectory: String,
        serverName: String = "cloudflare",
        listenPort: Int = TunnelEndpoints.DNSCRYPT_LISTEN_PORT,
        torSocksPort: Int = TunnelEndpoints.TOR_SOCKS_PORT,
        torDnsPort: Int = TunnelEndpoints.TOR_DNS_PORT,
        preferences: TunnelPreferences = TunnelPreferences(),
    ): String {
        val bootstrap = "${TunnelEndpoints.LOOPBACK}:$torDnsPort"
        val proxy =
            "socks5://${TunnelEndpoints.SOCKS_DNSCRYPT_USER}:${TunnelEndpoints.SOCKS_DNSCRYPT_PASS}" +
                "@${TunnelEndpoints.LOOPBACK}:$torSocksPort"
        val name = serverName.ifBlank { preferences.dnsCryptServerName }
        return """
            # Generated by OnionVPN — DNSCrypt upstream forced through Tor (dedicated SocksPort).
            # MITM hardening: ephemeral keys, no TLS tickets, Tor-only bootstrap, blocked DoH/captive.
            listen_addresses = ['${TunnelEndpoints.LOOPBACK}:$listenPort']
            max_clients = 128
            ipv4_servers = true
            ipv6_servers = false
            block_ipv6 = true
            dnscrypt_ephemeral_keys = true
            tls_disable_session_tickets = true
            tls_cipher_suite = [52393, 49199]

            require_dnssec = ${preferences.dnsCryptRequireDnssec}
            require_nolog = ${preferences.dnsCryptRequireNoLog}
            require_nofilter = ${preferences.dnsCryptRequireNoFilter}

            force_tcp = ${preferences.dnsCryptForceTcp}
            timeout = 15000
            keepalive = 30
            cert_refresh_delay = 240

            # Upstream DNSCrypt server connections go through Tor SOCKS (isolated port).
            proxy = '$proxy'

            # Bootstrap and netprobe use Tor DNSPort only — never system / captive DNS.
            bootstrap_resolvers = ['$bootstrap']
            ignore_system_dns = true
            netprobe_address = '$bootstrap'
            netprobe_timeout = 500

            # Short local cache; negative answers expire fast (captive / MITM churn).
            cache = true
            cache_size = 256
            cache_min_ttl = 60
            cache_max_ttl = 600
            cache_neg_min_ttl = 10
            cache_neg_max_ttl = 60

            [blocked_names]
              blocked_names_file = '$BLOCKED_NAMES_FILE'

            [static]
              [static.'$name']
                stamp = '${stampFor(name)}'
        """.trimIndent() + "\n"
    }

    fun stampFor(serverName: String): String =
        knownServers[serverName] ?: knownServers.getValue("cloudflare")
}
