#!/usr/bin/env bash
# Detect aarch64 host tooling and write gradle/arm-host.local.properties
# so AGP uses native aapt2 (no x86_64 QEMU) and optionally a native JDK 21.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/gradle/arm-host.local.properties"
ARCH="$(uname -m)"

case "$ARCH" in
  aarch64|arm64) ;;
  *)
    echo "Host arch is $ARCH (not aarch64). Nothing to configure."
    exit 0
    ;;
esac

find_aapt2() {
  local c
  for c in \
    "${AAPT2_PATH:-}" \
    "${AAPT2_OVERRIDE:-}" \
    "${PREFIX:+$PREFIX/bin/aapt2}" \
    /usr/bin/aapt2 \
    "${ANDROID_HOME:+$ANDROID_HOME/build-tools/35.0.2/aapt2}" \
    "${ANDROID_HOME:+$ANDROID_HOME/build-tools/36.0.0/aapt2}" \
    "${ANDROID_SDK_ROOT:+$ANDROID_SDK_ROOT/build-tools/35.0.2/aapt2}"
  do
    [[ -n "$c" && -x "$c" ]] || continue
    # Prefer ELF aarch64 over x86_64 (file(1) when available).
    if command -v file >/dev/null 2>&1; then
      if file -b "$c" 2>/dev/null | grep -qiE 'x86-64|x86_64'; then
        continue
      fi
    fi
    printf '%s\n' "$c"
    return 0
  done
  return 1
}

find_jdk21() {
  local c
  for c in \
    "${JAVA_HOME:-}" \
    "${ORG_GRADLE_JAVA_HOME:-}" \
    "${PREFIX:+$PREFIX/lib/jvm/java-21-openjdk}" \
    /usr/lib/jvm/java-21-openjdk \
    /usr/lib/jvm/java-21-openjdk-arm64 \
    /usr/lib/jvm/temurin-21-jdk-arm64
  do
    [[ -n "$c" && -x "$c/bin/java" ]] || continue
    if "$c/bin/java" -version 2>&1 | grep -qE 'version "21'; then
      printf '%s\n' "$c"
      return 0
    fi
  done
  return 1
}

AAPT2="$(find_aapt2 || true)"
JDK="$(find_jdk21 || true)"

{
  echo "# Generated by scripts/configure-arm-host.sh — do not commit."
  echo "# Host arch: $ARCH"
  if [[ -n "$AAPT2" ]]; then
    echo "android.aapt2FromMavenOverride=$AAPT2"
  else
    echo "# android.aapt2FromMavenOverride=  # NOT FOUND — install aapt2 (Termux: pkg install aapt2)"
  fi
  if [[ -n "$JDK" ]]; then
    echo "org.gradle.java.home=$JDK"
  else
    echo "# org.gradle.java.home=  # optional aarch64 JDK 21"
  fi
} >"$OUT"

echo "Wrote $OUT"
[[ -n "$AAPT2" ]] && echo "  aapt2: $AAPT2" || echo "  aapt2: MISSING"
[[ -n "$JDK" ]] && echo "  JDK21: $JDK" || echo "  JDK21: (not set)"
echo
echo "Build with: ./scripts/gradlew-arm :app:assembleDebug"
echo "Or:          ./gradlew :app:assembleDebug   # settings.gradle.kts auto-loads $OUT"
